### ISSUE TITLE
Segfault when running in docker

### ISSUE THREAD

**Issue by hategan** [whole-tale/wt_sils#2]
Details TBD

**Comment by hategan** [comment]
I added a docker directory that builds a somewhat bare image then installs additional dependencies, sets things up, and, finally, runs the icon generator. 

https://github.com/whole-tale/wt_sils/tree/master/docker

At this point it worksforme.

@Xarthisius, can you give it a shot?

**Comment by Xarthisius** [comment]
I recreated your installation step by step in the original Dockerfile. I think the only difference wrt to what I had before is compiling pycairo by hand. Anyway, the issue is gone, thank you!
